title:       "Operating Systems 2021-1 (OS211)"
version:     "06/04/2021 (1)"
copyright:   "2021-2021"
description: >- 
  This Is How Me Do It!
  This Is How Me Do It!
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
google_analytics: "UA-89852122-6"
author:           "Alfina Megasiwi"
address:          "Jakarta"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://alfina-megasiwi.github.io/os211/"
urlcontact:       ""
urlgithub:        "https://github.com/alfina-megasiwi/os211/"
urlghpage:        "https://alfina-megasiwi.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

